Feature/30 create about page
pollmelo/fruitend pull request #35
Opened 2023-02-13 09:38 UTC by GrafBunsen

Added about page, 

### **Spellcheck needed !!!**

closing #30

2023-02-14 09:39 UTC, martincodes-de requested changes
wrong project

2023-02-14 09:39 UTC, martincodes-de commented on components/AboutText.vue
> +  <p class="text-gray-400 m-4">Halfway ist als Projekt für Software Engennering 2 an der HWR entstanden. Dabei war uns
Halfway???

2023-02-14 09:39 UTC, martincodes-de commented on components/AboutText.vue
> +  <p class="text-gray-400 m-4">Halfway ist als Projekt für Software Engennering 2 an der HWR entstanden. Dabei war uns
Software Engineering
Hochschule für Wirtschaft und Recht

2023-02-14 09:39 UTC, martincodes-de commented on components/AboutText.vue
> +    foodsharing.de
add link to foodsharing

2023-02-14 09:40 UTC, martincodes-de commented on components/AboutText.vue
> +  <p class="text-gray-400 m-4">Halfway ist als Projekt für Software Engennering 2 an der HWR entstanden. Dabei war uns
maybe add link to hochschule für wirtschaft und recht

2023-02-14 09:45 UTC, GrafBunsen commented on components/AboutText.vue
> +  <p class="text-gray-400 m-4">Halfway ist als Projekt für Software Engennering 2 an der HWR entstanden. Dabei war uns
fixed it, halway was my last genius project

2023-02-14 09:47 UTC, martincodes-de requested changes

2023-02-14 09:47 UTC, martincodes-de commented on pages/about.vue
> +import AboutText from "~/components/AboutText.vue";
no imports needed

2023-02-14 10:08 UTC, GrafBunsen commented on components/AboutText.vue
> +    foodsharing.de
yes boss

2023-02-14 10:13 UTC, GrafBunsen commented on pages/about.vue
> +import AboutText from "~/components/AboutText.vue";
done

2023-02-14 10:24 UTC, GrafBunsen commented on components/AboutText.vue
> +  <p class="text-gray-400 m-4">Halfway ist als Projekt für Software Engennering 2 an der HWR entstanden. Dabei war uns
done

2023-02-14 11:01 UTC, martincodes-de approved these changes
LGTM

2023-02-15 10:18 UTC, emsbe requested changes

2023-02-15 10:18 UTC, emsbe commented on components/AboutText.vue
> +    entstanden. Dabei war uns wichtig ein Projekt zu finden welches auch über den Kurs hinaus bestehen bleibt. Deswegen
```suggestion
    entstanden. Dabei war uns wichtig ein Projekt zu finden, welches auch über den Kurs hinaus bestehen bleibt. Deswegen
```

2023-02-15 10:18 UTC, emsbe commented on components/AboutText.vue
> +    an der Website fehlt. Deswegen haben wir beschlossen ein solches Feature entwickeln.</p>
```suggestion
    an der Website fehlt. Deswegen haben wir beschlossen, ein solches Feature entwickeln.</p>
```

2023-02-15 10:18 UTC, emsbe commented on components/AboutText.vue
> +    ist können die Entwickler/innen durch diese Votes aus der Community entscheiden, welche Verbesserungen priorisiert
```suggestion
    ist, können die Entwickler/innen durch diese Votes aus der Community entscheiden, welche Verbesserungen priorisiert
```

2023-02-15 10:18 UTC, emsbe commented on components/AboutTeam.vue
> +  </div>
```suggestion
  </div>
  <br>
```

2023-02-15 10:24 UTC, emsbe approved these changes

2023-02-15 10:27 UTC, merged