add up- and downvote functionallity
pollmelo/fruitend pull request #44
Opened 2023-03-01 10:51 UTC by martincodes-de

this pr adds up and downvote functionallity to poll list item
 closes #36

2023-03-02 11:19 UTC, NiklasBGit commented
I think I added this by accident in #26 so this one can be closed?

2023-03-03 13:45 UTC, GrafBunsen requested changes
upvote count is not updated when clicking, new value only loads after refresh (on index page)

2023-03-03 13:45 UTC, GrafBunsen commented on components/PollListItem.vue
> +          body: { description: true, pollId: this.id }
```suggestion
          body: { description: true, pollId: this.id },

```

2023-03-03 13:52 UTC, GrafBunsen commented
dont merge, feature might be obsolete

2023-03-03 16:37 UTC, GrafBunsen commented
see comment above

2023-03-03 16:37 UTC, closed without merging